const people = [
  {
    id: 0,
    name: "TestName0",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 1,
    name: "TestName1",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 2,
    name: "TestName2",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 3,
    name: "TestName3",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 4,
    name: "TestName4",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 5,
    name: "TestName5",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 6,
    name: "TestName6",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 7,
    name: "TestName7",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 8,
    name: "TestName8",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 9,
    name: "TestName9",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 10,
    name: "TestName10",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 11,
    name: "TestName11",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 12,
    name: "TestName12",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 13,
    name: "TestName13",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 14,
    name: "TestName14",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 15,
    name: "TestName15",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 16,
    name: "TestName16",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 17,
    name: "TestName17",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 18,
    name: "TestName18",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 19,
    name: "TestName19",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 20,
    name: "TestName20",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 21,
    name: "TestName21",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 22,
    name: "TestName22",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 23,
    name: "TestName23",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 24,
    name: "TestName24",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 25,
    name: "TestName25",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 26,
    name: "TestName26",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
  {
    id: 27,
    name: "TestName27",
    jobTitle: "TestTitle",
    department: "TestDepart",
    gender: "TestGender",
  },
];

export { people };
